services:
  _defaults:
    autowire: true

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  Paragin\Cli\Application:
    public: true
    arguments:
    - !tagged command