parameters:
  caesura: 0.7
  floor: 0.2

services:
  _defaults:
    autowire: true
    bind:
      $varDir: '%var_dir%'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  Paragin\Cli\:
    resource: '../src'
    exclude:
      - '../src/Domain/Result/{Result,ResultCollection}'
      - '../src/Exception'

  Paragin\Cli\Application:
    public: true
    arguments:
      - !tagged_iterator command

  Paragin\Cli\Domain\Result\Grader\ResultGrader:
    bind:
      $caesura: '%caesura%'
      $floor: '%floor%'